[package]
name = "rust-prec"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcon = { version = "0.6.0", features = ["rt-tokio"], default-features = false }
async-log-watcher = "0.0.1"
steamlocate = "1.2.1"
tokio = { version = "1.28.2", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "full",
] }
